name: Deploy

on:
  push:
    branches: [ server ]

jobs:
  Deploy:
    runs-on: self-hosted

    steps:
    - name: Deploying ..
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          git pull
          npm i
          docker restart thijmenheuvelink.nl
